using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;

namespace sms.Data
{
    public class GenerateData
    {
        private readonly sms.Data.ApplicationDbContext _context;
        public GenerateData(sms.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        //Save autogenerated lessons and manually entered marks to text files to later insert into SeedData classes
        //The sb.Replace() is only valid for one time. Each db reseed the Ids change a bit
        public void Save()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            string text = String.Empty;
            var lessons = _context.Lessons.AsNoTracking().ToList();
            foreach (var lesson in lessons)
            {
                sb.Append($"new Lesson {{\nDay = \"{lesson.Day}\",\nSlot = {lesson.Slot},\nRoom = \"{lesson.Room}\",\nGradeId = {lesson.GradeId},\nSubjectId = {lesson.SubjectId},\nTeacherId = {lesson.TeacherId}\n}},\n");
            }
            ReplaceGrades(sb);
            ReplaceSubjects(sb);
            ReplaceTeachers(sb);

            File.WriteAllTextAsync("Lessons.txt", sb.ToString());

            var gradebooks = _context.Gradebooks.AsNoTracking().ToList();
            sb.Clear();
            foreach(var gradebook in gradebooks)
            {
                sb.Append($"new Gradebook\n{{\nLessonDate = new DateTime({gradebook.LessonDate.Year}, {gradebook.LessonDate.Month}, {gradebook.LessonDate.Day}),\nMark = \"{gradebook.Mark}\",\nStudentId = {gradebook.StudentId},\nSubjectId = {gradebook.SubjectId},\nTeacherId = {gradebook.TeacherId}\n}},\n");
            }

            ReplaceSubjects(sb);
            ReplaceTeachers(sb);
            ReplaceStudents(sb);

            File.WriteAllTextAsync("Gradebooks.txt", sb.ToString());
            
        }
        public void ReplaceTeachers(StringBuilder sb)
        {
            sb.Replace("TeacherId = 1\n", "Teacher = lavrychenko\n");
            sb.Replace("TeacherId = 2\n", "Teacher = lonska\n");
            sb.Replace("TeacherId = 3\n", "Teacher = vlasiuk\n");
            sb.Replace("TeacherId = 4\n", "Teacher = hnots\n");
            sb.Replace("TeacherId = 5\n", "Teacher = mandro\n");
            sb.Replace("TeacherId = 6\n", "Teacher = nanivska\n");
            sb.Replace("TeacherId = 7\n", "Teacher = yeroshkina\n");
            sb.Replace("TeacherId = 8\n", "Teacher = nimchenko\n");
            sb.Replace("TeacherId = 9\n", "Teacher = plotnik\n");
            sb.Replace("TeacherId = 10\n", "Teacher = zadorozhnia\n");
            sb.Replace("TeacherId = 11\n", "Teacher = symonenko_ov\n");
            sb.Replace("TeacherId = 12\n", "Teacher = horlova\n");
            sb.Replace("TeacherId = 13\n", "Teacher = bondarenko\n");
            sb.Replace("TeacherId = 14\n", "Teacher = manko\n");
            sb.Replace("TeacherId = 15\n", "Teacher = honcharuk\n");
            sb.Replace("TeacherId = 16\n", "Teacher = lisichkina\n");
            sb.Replace("TeacherId = 17\n", "Teacher = vasylieva\n");
            sb.Replace("TeacherId = 18\n", "Teacher = kurach\n");
            sb.Replace("TeacherId = 19\n", "Teacher = martynenko\n");
            sb.Replace("TeacherId = 20\n", "Teacher = boyarska\n");
            sb.Replace("TeacherId = 21\n", "Teacher = dybka\n");
            sb.Replace("TeacherId = 22\n", "Teacher = ponomarenko\n");
            sb.Replace("TeacherId = 23\n", "Teacher = synko\n");
            sb.Replace("TeacherId = 24\n", "Teacher = kholodiuk\n");
            sb.Replace("TeacherId = 25\n", "Teacher = kyrianov\n");
            sb.Replace("TeacherId = 26\n", "Teacher = shafran\n");
            sb.Replace("TeacherId = 27\n", "Teacher = bulachok\n");
            sb.Replace("TeacherId = 28\n", "Teacher = smychnikova\n");
            sb.Replace("TeacherId = 29\n", "Teacher = sovenko\n");
            sb.Replace("TeacherId = 30\n", "Teacher = shulga\n");
            sb.Replace("TeacherId = 31\n", "Teacher = zviahelskyi\n");
            sb.Replace("TeacherId = 32\n", "Teacher = havro\n");
            sb.Replace("TeacherId = 33\n", "Teacher = symonenko_op\n");
            sb.Replace("TeacherId = 34\n", "Teacher = kyrylusha\n");
            sb.Replace("TeacherId = 35\n", "Teacher = verbova_nv\n");
            sb.Replace("TeacherId = 36\n", "Teacher = verbova_vo\n");
            sb.Replace("TeacherId = 37\n", "Teacher = melnychuk\n");
            sb.Replace("TeacherId = 38\n", "Teacher = slavov\n");
            sb.Replace("TeacherId = 39\n", "Teacher = tverdokhlibova\n");
            sb.Replace("TeacherId = 40\n", "Teacher = shevchenko\n");
            sb.Replace("TeacherId = 41\n", "Teacher = moskalenko\n");
            sb.Replace("TeacherId = 42\n", "Teacher = sulyma\n");
        }
        public void ReplaceSubjects(StringBuilder sb)
        {
            sb.Replace("SubjectId = 1,", "Subject = nature_primary,");
            sb.Replace("SubjectId = 2,", "Subject = ukrlit,");
            sb.Replace("SubjectId = 3,", "Subject = ukrainian,");
            sb.Replace("SubjectId = 4,", "Subject = crafts_primary,");
            sb.Replace("SubjectId = 5,", "Subject = music,");
            sb.Replace("SubjectId = 6,", "Subject = algebra,");
            sb.Replace("SubjectId = 7,", "Subject = iexplore,");
            sb.Replace("SubjectId = 8,", "Subject = iandworld,");
            sb.Replace("SubjectId = 9,", "Subject = geometry,");
            sb.Replace("SubjectId = 10,", "Subject = writing,");
            sb.Replace("SubjectId = 11,", "Subject = ukrainian_primary,");
            sb.Replace("SubjectId = 12,", "Subject = health_primary,");
            sb.Replace("SubjectId = 13,", "Subject = design,");
            sb.Replace("SubjectId = 14,", "Subject = physics,");
            sb.Replace("SubjectId = 15,", "Subject = astronomy,");
            sb.Replace("SubjectId = 16,", "Subject = literacy,");
            sb.Replace("SubjectId = 17,", "Subject = pt,");
            sb.Replace("SubjectId = 18,", "Subject = civildef,");
            sb.Replace("SubjectId = 19,", "Subject = maths_primary,");
            sb.Replace("SubjectId = 20,", "Subject = litreading,");
            sb.Replace("SubjectId = 21,", "Subject = individual,");
            sb.Replace("SubjectId = 22,", "Subject = chemistry,");
            sb.Replace("SubjectId = 23,", "Subject = maths,");
            sb.Replace("SubjectId = 24,", "Subject = crafts,");
            sb.Replace("SubjectId = 25,", "Subject = finearts,");
            sb.Replace("SubjectId = 26,", "Subject = reading,");
            sb.Replace("SubjectId = 27,", "Subject = it,");
            sb.Replace("SubjectId = 28,", "Subject = jurisprudence,");
            sb.Replace("SubjectId = 29,", "Subject = english,");
            sb.Replace("SubjectId = 30,", "Subject = french,");
            sb.Replace("SubjectId = 31,", "Subject = biology,");
            sb.Replace("SubjectId = 32,", "Subject = nature,");
            sb.Replace("SubjectId = 33,", "Subject = civileduc,");
            sb.Replace("SubjectId = 34,", "Subject = wliterature,");
            sb.Replace("SubjectId = 35,", "Subject = arts,");
            sb.Replace("SubjectId = 36,", "Subject = geography,");
            sb.Replace("SubjectId = 37,", "Subject = history,");
            sb.Replace("SubjectId = 38,", "Subject = uhistory,");
            sb.Replace("SubjectId = 39,", "Subject = whistory,");
            sb.Replace("SubjectId = 40,", "Subject = finearts_primary,");
            sb.Replace("SubjectId = 41,", "Subject = health,");
        }
        public void ReplaceGrades(StringBuilder sb)
        {
            sb.Replace("GradeId = 1,", "Grade = a1,");
            sb.Replace("GradeId = 2,", "Grade = b11,");
            sb.Replace("GradeId = 3,", "Grade = a11,");
            sb.Replace("GradeId = 4,", "Grade = b10,");
            sb.Replace("GradeId = 5,", "Grade = a10,");
            sb.Replace("GradeId = 6,", "Grade = b9,");
            sb.Replace("GradeId = 7,", "Grade = b8,");
            sb.Replace("GradeId = 8,", "Grade = a8,");
            sb.Replace("GradeId = 9,", "Grade = b7,");
            sb.Replace("GradeId = 10,", "Grade = a7,");
            sb.Replace("GradeId = 11,", "Grade = b6,");
            sb.Replace("GradeId = 12,", "Grade = a9,");
            sb.Replace("GradeId = 13,", "Grade = b5,");
            sb.Replace("GradeId = 14,", "Grade = a5,");
            sb.Replace("GradeId = 15,", "Grade = b4,");
            sb.Replace("GradeId = 16,", "Grade = a4,");
            sb.Replace("GradeId = 17,", "Grade = b3,");
            sb.Replace("GradeId = 18,", "Grade = a3,");
            sb.Replace("GradeId = 19,", "Grade = b2,");
            sb.Replace("GradeId = 20,", "Grade = a2,");
            sb.Replace("GradeId = 21,", "Grade = b1,");
            sb.Replace("GradeId = 22,", "Grade = a6,");
        }
        public void ReplaceStudents(StringBuilder sb)
        {
            sb.Replace("StudentId = 1,", "Student = s001,");
            sb.Replace("StudentId = 2,", "Student = s056,");
            sb.Replace("StudentId = 3,", "Student = s081,");
            sb.Replace("StudentId = 4,", "Student = s080,");
            sb.Replace("StudentId = 5,", "Student = s079,");
            sb.Replace("StudentId = 6,", "Student = s078,");
            sb.Replace("StudentId = 7,", "Student = s077,");
            sb.Replace("StudentId = 8,", "Student = s076,");
            sb.Replace("StudentId = 9,", "Student = s008,");
            sb.Replace("StudentId = 10,", "Student = s075,");
            sb.Replace("StudentId = 11,", "Student = s074,");
            sb.Replace("StudentId = 12,", "Student = s073,");
            sb.Replace("StudentId = 13,", "Student = s072,");
            sb.Replace("StudentId = 14,", "Student = s071,");
            sb.Replace("StudentId = 15,", "Student = s070,");
            sb.Replace("StudentId = 16,", "Student = s069,");
            sb.Replace("StudentId = 17,", "Student = s083,");
            sb.Replace("StudentId = 18,", "Student = s082,");
            sb.Replace("StudentId = 19,", "Student = s067,");
            sb.Replace("StudentId = 20,", "Student = s068,");
            sb.Replace("StudentId = 21,", "Student = s085,");
            sb.Replace("StudentId = 22,", "Student = s097,");
            sb.Replace("StudentId = 23,", "Student = s096,");
            sb.Replace("StudentId = 24,", "Student = s095,");
            sb.Replace("StudentId = 25,", "Student = s094,");
            sb.Replace("StudentId = 26,", "Student = s093,");
            sb.Replace("StudentId = 27,", "Student = s092,");
            sb.Replace("StudentId = 28,", "Student = s030,");
            sb.Replace("StudentId = 29,", "Student = s031,");
            sb.Replace("StudentId = 30,", "Student = s040,");
            sb.Replace("StudentId = 31,", "Student = s091,");
            sb.Replace("StudentId = 32,", "Student = s090,");
            sb.Replace("StudentId = 33,", "Student = s089,");
            sb.Replace("StudentId = 34,", "Student = s088,");
            sb.Replace("StudentId = 35,", "Student = s087,");
            sb.Replace("StudentId = 36,", "Student = s086,");
            sb.Replace("StudentId = 37,", "Student = s084,");
            sb.Replace("StudentId = 38,", "Student = s066,");
            sb.Replace("StudentId = 39,", "Student = s099,");
            sb.Replace("StudentId = 40,", "Student = s065,");
            sb.Replace("StudentId = 41,", "Student = s004,");
            sb.Replace("StudentId = 42,", "Student = s003,");
            sb.Replace("StudentId = 43,", "Student = s002,");
            sb.Replace("StudentId = 44,", "Student = s045,");
            sb.Replace("StudentId = 45,", "Student = s044,");
            sb.Replace("StudentId = 46,", "Student = s032,");
            sb.Replace("StudentId = 47,", "Student = s033,");
            sb.Replace("StudentId = 48,", "Student = s034,");
            sb.Replace("StudentId = 49,", "Student = s035,");
            sb.Replace("StudentId = 50,", "Student = s043,");
            sb.Replace("StudentId = 51,", "Student = s036,");
            sb.Replace("StudentId = 52,", "Student = s042,");
            sb.Replace("StudentId = 53,", "Student = s037,");
            sb.Replace("StudentId = 54,", "Student = s038,");
            sb.Replace("StudentId = 55,", "Student = s041,");
            sb.Replace("StudentId = 56,", "Student = s046,");
            sb.Replace("StudentId = 57,", "Student = s047,");
            sb.Replace("StudentId = 58,", "Student = s048,");
            sb.Replace("StudentId = 59,", "Student = s049,");
            sb.Replace("StudentId = 60,", "Student = s064,");
            sb.Replace("StudentId = 61,", "Student = s063,");
            sb.Replace("StudentId = 62,", "Student = s062,");
            sb.Replace("StudentId = 63,", "Student = s061,");
            sb.Replace("StudentId = 64,", "Student = s060,");
            sb.Replace("StudentId = 65,", "Student = s059,");
            sb.Replace("StudentId = 66,", "Student = s058,");
            sb.Replace("StudentId = 67,", "Student = s098,");
            sb.Replace("StudentId = 68,", "Student = s057,");
            sb.Replace("StudentId = 69,", "Student = s005,");
            sb.Replace("StudentId = 70,", "Student = s055,");
            sb.Replace("StudentId = 71,", "Student = s054,");
            sb.Replace("StudentId = 72,", "Student = s053,");
            sb.Replace("StudentId = 73,", "Student = s052,");
            sb.Replace("StudentId = 74,", "Student = s051,");
            sb.Replace("StudentId = 75,", "Student = s050,");
            sb.Replace("StudentId = 76,", "Student = s006,");
            sb.Replace("StudentId = 77,", "Student = s007,");
            sb.Replace("StudentId = 78,", "Student = s039,");
            sb.Replace("StudentId = 79,", "Student = s100,");
            sb.Replace("StudentId = 80,", "Student = s124,");
            sb.Replace("StudentId = 81,", "Student = s125,");
            sb.Replace("StudentId = 82,", "Student = s126,");
            sb.Replace("StudentId = 83,", "Student = s128,");
            sb.Replace("StudentId = 84,", "Student = s129,");
            sb.Replace("StudentId = 85,", "Student = s130,");
            sb.Replace("StudentId = 86,", "Student = s131,");
            sb.Replace("StudentId = 87,", "Student = s132,");
            sb.Replace("StudentId = 88,", "Student = s029,");
            sb.Replace("StudentId = 89,", "Student = s009,");
            sb.Replace("StudentId = 90,", "Student = s010,");
            sb.Replace("StudentId = 91,", "Student = s123,");
            sb.Replace("StudentId = 92,", "Student = s011,");
            sb.Replace("StudentId = 93,", "Student = s024,");
            sb.Replace("StudentId = 94,", "Student = s023,");
            sb.Replace("StudentId = 95,", "Student = s022,");
            sb.Replace("StudentId = 96,", "Student = s021,");
            sb.Replace("StudentId = 97,", "Student = s012,");
            sb.Replace("StudentId = 98,", "Student = s013,");
            sb.Replace("StudentId = 99,", "Student = s014,");
            sb.Replace("StudentId = 100,", "Student = s015,");
            sb.Replace("StudentId = 101,", "Student = s018,");
            sb.Replace("StudentId = 102,", "Student = s019,");
            sb.Replace("StudentId = 103,", "Student = s020,");
            sb.Replace("StudentId = 104,", "Student = s025,");
            sb.Replace("StudentId = 105,", "Student = s122,");
            sb.Replace("StudentId = 106,", "Student = s127,");
            sb.Replace("StudentId = 107,", "Student = s120,");
            sb.Replace("StudentId = 108,", "Student = s112,");
            sb.Replace("StudentId = 109,", "Student = s027,");
            sb.Replace("StudentId = 110,", "Student = s111,");
            sb.Replace("StudentId = 111,", "Student = s110,");
            sb.Replace("StudentId = 112,", "Student = s109,");
            sb.Replace("StudentId = 113,", "Student = s108,");
            sb.Replace("StudentId = 114,", "Student = s121,");
            sb.Replace("StudentId = 115,", "Student = s107,");
            sb.Replace("StudentId = 116,", "Student = s105,");
            sb.Replace("StudentId = 117,", "Student = s104,");
            sb.Replace("StudentId = 118,", "Student = s103,");
            sb.Replace("StudentId = 119,", "Student = s102,");
            sb.Replace("StudentId = 120,", "Student = s028,");
            sb.Replace("StudentId = 121,", "Student = s101,");
            sb.Replace("StudentId = 122,", "Student = s106,");
            sb.Replace("StudentId = 123,", "Student = s114,");
            sb.Replace("StudentId = 124,", "Student = s113,");
            sb.Replace("StudentId = 125,", "Student = s026,");
            sb.Replace("StudentId = 126,", "Student = s119,");
            sb.Replace("StudentId = 127,", "Student = s115,");
            sb.Replace("StudentId = 128,", "Student = s016,");
            sb.Replace("StudentId = 129,", "Student = s017,");
            sb.Replace("StudentId = 130,", "Student = s116,");
            sb.Replace("StudentId = 131,", "Student = s117,");
            sb.Replace("StudentId = 132,", "Student = s118,");
        }
        public void GenerateInventory()
        {
            Random random = new Random();
            string[] lines = System.IO.File.ReadAllLines(@"inventory.txt");
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            string text = String.Empty;

            foreach (string line in lines)
            {
                sb.Append($"            new Inventory{Environment.NewLine}            {{{Environment.NewLine}                " +
                    $"Name = \"{line}\",{Environment.NewLine}                InventoryNumber = {random.Next(11111111,100000000)}," +
                    $"{Environment.NewLine}                Quantity = {random.Next(1, 51)},{Environment.NewLine}                " +
                    $"Price = {RandomDecimal(random, 100, 3000)}m,{Environment.NewLine}                " +
                    $"InventoryDate = new DateTime({random.Next(DateTime.Now.Year - 10, DateTime.Now.Year + 1)}, {random.Next(1, 13)}, {random.Next(1, 29)})" +
                    $"{Environment.NewLine}            }},{Environment.NewLine}");
                File.WriteAllText("inventory_seed.txt", sb.ToString());
            }

        }
        public decimal RandomDecimal(Random rnd, double min, double max)
        {
            return Decimal.Round((decimal)(rnd.NextDouble() * (max - min) + min), 2); ;
        }
    }
}
