name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: schoolmanagementapp
  WORKING_DIRECTORY: .

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: sms
    - name: Build
      run: dotnet build --no-restore
      working-directory: sms
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: smsTest
    - name: Publish
      run: dotnet publish sms/sms.csproj -c Release -o website
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.SCHOOLMANAGEMENTAPP_WEBAPP_SECRET }}
        package: '${{ env.WORKING_DIRECTORY }}/website'